version: 2

build:
  os: ubuntu-20.04

sphinx:
  configuration: docs/mkdocs.yml
  builder: mkdocs
  install_requirements: poetry install

python:
  install:
    # Install dependencies from pyproject.toml
    - requirements: pyproject.toml
    # Optional: install dev dependencies for doc generation
    - requirements: docs/requirements.txt

formats:
  - html

project:
  docs: docs/milanesas
  source: milanesas

# Optional, define the version to link to when building docs
version: 0.1.9


