[tool.poetry]
name = "milanesas"
version = "0.1.0"
description = ""
authors = ["Torrez, Milton <torrez.mn@gmail.com>"]
readme = "README.md"
packages = [
    { include = "milanesas" },  # For code in a custom directory named "mypackage"
]


[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
