site_name: Milanesas 
site_url: https://example.com/

nav:
  - Home: index.md
  - About: about.md
  - Nose que mierda!: no_se_que.md

theme:
  name: readthedocs 
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.livesearch
    - search.fuzzy
    - search.highlight
  # Customize the search bar position (optional)
  search.placeholder: "Search documentation..."
  search.icon: material/magnifying-glass

plugins:
  - search

