name: Poetry Publish Dry Run (test branch)

on:
  push:
    branches: [ test ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: Pipy
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your desired Python version
      - name: Install Poetry
        run: |
          python -m pip install poetry
      - name: Check Poetry project
        run: poetry config
      - name: Install dependencies
        run: poetry install

  build-package:
    needs: build-and-test  # Ensure tests pass before building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build package
        run: poetry build

  publish-dry-run:
    needs: build-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Poetry for testpypi
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PIPY_KEY }}
          poetry config pypi-token.pypi ${{ secrets.TEST_PIPY_KEY }}
      - name: Patch version
        run: poetry version patch
      - name: Run Poetry Publish dry-run
        run: poetry publish -r testpypi --build --dry-run
      - name: Finish
        run: echo "ITS ALL OK"

