name: Poetry Publish Dry Run (test branch)

on:
  push:
    branches: [ test ]


jobs:
  build:
    runs-on: ubuntu-latest
    environment: Pipy
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your desired Python version
      - name: Install Poetry
        run: |
          python -m pip install poetry
      - name: Check Poetry project
        run: poetry config
      - name: Install dependencies
        run: poetry install
      - name: Build package.
        run: poetry build
      - name: Config poetry repo.
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - name: Set pipy key.
        run: poetry config pypi-token.testpypi ${{ secrets.TEST_PIPY_KEY }}
      - name: Patch vercion
        run: poetry version patch
      - name: Run Poetry Publish dry-run
        run: poetry publish -r testpypi --build 


